IEProject1/Models/Content.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public string ContentName { get; set; }
        public string ImageName { get; set; }
        public Nullable<decimal> Popularity { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Comment { get; set; }
    
        public virtual Field Field { get; set; }
    }
}

IEProject1/Controllers/ContentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using IEProject1.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IEProject1.Controllers
{
    public class ContentsController : Controller
    {
        private IEProject1Entities db = new IEProject1Entities();

        // GET: Contents
        public ActionResult Index()
        {
            using (StreamReader reader = new StreamReader(Server.MapPath("~/Content/twitterTrends.json")))
            {

                string result = reader.ReadToEnd();
                //var json = JObject.Parse(result);
                JArray jsonArray = JArray.Parse(result);
                var trend = jsonArray[0]["trends"].ToString();

                var trends = JsonConvert.DeserializeObject<List<Trend>>(trend).Take(12);

                ViewData["trends"] = trends;
            }


            var contents = db.Content.Include(c => c.Field).Where(s => s.Rank < 9).OrderBy(a => a.Rank);

            ViewData["contents"] = contents;
            return View();

           // return View(contents.ToList());
        }

        // GET: Contents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Content.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // GET: Contents/Create
        public ActionResult Create()
        {
            ViewBag.TypeId = new SelectList(db.Field, "Id", "FieldName");
            return View();
        }

        // POST: Contents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ContentName,ImageName,Popularity,Rank,TypeId,Comment")] Content content)
        {
            if (ModelState.IsValid)
            {
                db.Content.Add(content);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TypeId = new SelectList(db.Field, "Id", "FieldName", content.TypeId);
            return View(content);
        }

        // GET: Contents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else if (id == 1)
            {
                ViewData["Message"] = "Places";
            }
            else if (id == 2)
            {
                ViewData["Message"] = "RPlaces";
            }
            else if (id == 3)
            {
                ViewData["Message"] = "YPlaces";
            }
            //else if (id == 4)
            //{
            //    ViewData["Message"] = "Culture";
            //}
            //Content content = db.Contents.Find(id);
            var content = db.Content.Where(s => s.TypeId == id);
            
            if (content == null)
            {
                return HttpNotFound();
            }
            ViewData["content"] = content;
            //ViewBag.TypeId = new SelectList(db.Fields, "Id", "FieldName", content.TypeId);
            //return View(content.ToList());
            return View();
        }

        // POST: Contents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ContentName,ImageName,Popularity,Rank,TypeId,Comment")] Content content)
        {
            if (ModelState.IsValid)
            {
                db.Entry(content).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeId = new SelectList(db.Field, "Id", "FieldName", content.TypeId);
            return View(content);
        }

        // GET: Contents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = db.Content.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: Contents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Content content = db.Content.Find(id);
            db.Content.Remove(content);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Page1()
        {

            using (StreamReader reader = new StreamReader(Server.MapPath("~/Content/twitterTrends.json")))
            {

                string result = reader.ReadToEnd();
                //var json = JObject.Parse(result);
                JArray jsonArray = JArray.Parse(result);
                var trend = jsonArray[0]["trends"].ToString();

                var trends = JsonConvert.DeserializeObject<List<Trend>>(trend).Take(12);

                ViewData["trends"] = trends;
            }


            var contents = db.Content.Include(c => c.Field).Where(s => s.Rank < 9).OrderBy(a => a.Rank);

            ViewData["contents"] = contents;
            return View();

            // return View(contents.ToList());
        }

        public string GetTwitterTrends()
        {
            // oauth application keys
            string oauth_token = "278606942-WGdc2l5nXNtYENK14v3bBBQlUfZvYJSDfBFV8IZ1";
            string oauth_token_secret = "8gyATwlCkj26HlPhZCRfkWSu3OdVVg6bsL85jd3l1IFSQ";

            string oauth_consumer_key = "OhOhEUTcnQAnJpNg8NvzwY9bh";
            string oauth_consumer_secret = "qBgfNz1q9jrb1QFvuoXzpuT6H6qmeALpf2nd7MAIgJ56QSulm8";

            var oauth_version = "1.0";
            var oauth_signature_method = "HMAC-SHA1";
            var oauth_nonce = Convert.ToBase64String(new ASCIIEncoding().GetBytes(DateTime.Now.Ticks.ToString()));
            var timeSpan = DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
            var oauth_timestamp = Convert.ToInt64(timeSpan.TotalSeconds).ToString();
            var resource_url = "https://api.twitter.com/1.1/trends/place.json?id=1103816";

            //encrypted oAuth signature
            var baseFormat = "oauth_consumer_key={0}&oauth_nonce={1}&oauth_signature_method={2}" +
                "&oauth_timestamp={3}&oauth_token={4}&oauth_version={5}";

            var baseString = string.Format(baseFormat,
                                        oauth_consumer_key,
                                        oauth_nonce,
                                        oauth_signature_method,
                                        oauth_timestamp,
                                        oauth_token,
                                        oauth_version
                                        );

            baseString = string.Concat("GET&", Uri.EscapeDataString(resource_url),
                         "&", Uri.EscapeDataString(baseString));

            //Encrypt data

            var compositeKey = string.Concat(Uri.EscapeDataString(oauth_consumer_secret),
                        "&", Uri.EscapeDataString(oauth_token_secret));

            string oauth_signature;
            using (HMACSHA1 hasher = new HMACSHA1(ASCIIEncoding.ASCII.GetBytes(compositeKey)))
            {
                oauth_signature = Convert.ToBase64String(hasher.ComputeHash(ASCIIEncoding.ASCII.GetBytes(baseString)));
            }

            //Finish Authentification header

            var headerFormat = "OAuth oauth_nonce=\"{0}\", oauth_signature_method=\"{1}\", " +
                   "oauth_timestamp=\"{2}\", oauth_consumer_key=\"{3}\", " +
                   "oauth_token=\"{4}\", oauth_signature=\"{5}\", " +
                   "oauth_version=\"{6}\"";

            var authHeader = string.Format(headerFormat,
                                    Uri.EscapeDataString(oauth_nonce),
                                    Uri.EscapeDataString(oauth_signature_method),
                                    Uri.EscapeDataString(oauth_timestamp),
                                    Uri.EscapeDataString(oauth_consumer_key),
                                    Uri.EscapeDataString(oauth_token),
                                    Uri.EscapeDataString(oauth_signature),
                                    Uri.EscapeDataString(oauth_version)
                            );

            //Disable exprect 100 continue header
            ServicePointManager.Expect100Continue = false;

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(resource_url);
            request.UseDefaultCredentials = true;
            request.PreAuthenticate = true;
            request.Credentials = CredentialCache.DefaultCredentials;
            request.Headers.Add("Authorization", authHeader);
            request.Method = "GET";

            WebResponse response = request.GetResponse();
            string responseData;

IEProject1/Views/Contents/Create.cshtml
@model IEProject1.Models.Content

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml";
}

<title>Activity Statistics</title>
<!-- Following Menu -->
<div class="ui large top fixed menu">
    <div class="ui container">
        <a href="@Url.Action("Page1", "Contents")" class="item">Home</a>
        @*<a href="@Url.Action("Edit", "Contents", new { id = 1 })" class="item">Sports</a>
            <a href="@Url.Action("Edit", "Contents", new { id = 2 })" class="item">Religion</a>
            <a href="@Url.Action("Edit", "Contents", new { id = 3 })" class="item">Yoga</a>
            <a href="@Url.Action("Edit", "Contents", new { id = 4 })" class="item">Culture</a>
            <a href="@Url.Action("Create", "Contents")" class="item">Statistics</a>*@
        <a href="@Url.Action("Index", "Places")" class="item">Sports</a>
        <a href="@Url.Action("Index", "RPlaces")" class="item">Religion</a>
        <a href="@Url.Action("Index", "YPlaces")" class="item">Yoga&Taichi</a>
        <a href="@Url.Action("Details", "Places")" class="item">Food</a>
    </div>
</div>

<div class="ui container" style="padding-top:5%">
    <div class="ui three column grid">
        <div class="row">
            <img src="@Url.Content("~/Content/Images/sport1.png")">
        </div>

        <div class="row">
            <img src="@Url.Content("~/Content/Images/sports2.png")">
        </div>

        <div class="row">
            <img src="@Url.Content("~/Content/Images/cuture.png")">
        </div>

    </div>
</div>

IEProject1/Views/Contents/Delete.cshtml
@model IEProject1.Models.Content

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Content</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Popularity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Popularity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Field.FieldName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Field.FieldName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IEProject1/Views/Contents/Details.cshtml
@model IEProject1.Models.Content

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Content</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Popularity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Popularity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Field.FieldName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Field.FieldName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IEProject1/Views/Contents/Edit.cshtml
@model IEnumerable<IEProject1.Models.Content>
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml";
}

<!-- Following Menu -->
<div class="ui large top fixed menu">
    <div class="ui container">
        <a href="@Url.Action("Index", "Contents")" class="item">Home</a>
        @*<a href="@Url.Action("Edit", "Contents", new { id= 1 })" class="item">Sports</a>
        <a href="@Url.Action("Edit", "Contents", new { id= 2 })" class="item">Religion</a>
        <a href="@Url.Action("Edit", "Contents", new { id= 3 })" class="item">Yoga</a>
        <a href="@Url.Action("Edit", "Contents", new { id= 4 })" class="item">Culture</a>
        <a href="@Url.Action("Create", "Contents")" class="item">Statistics</a>*@
        <a href="@Url.Action("Index", "Places")" class="item">Sports</a>
        <a href="@Url.Action("Index", "RPlaces")" class="item">Religion</a>
        <a href="@Url.Action("Index", "YPlaces")" class="item">Yoga&Taichi</a>
        <a href="@Url.Action("Edit", "Contents", new { id= 4 })" class="item">Culture</a>
        @*<div class="right menu">
        <div class="item">
            <a class="ui button">Log in</a>
        </div>
        <div class="item">
            <a class="ui primary button">Sign Up</a>
        </div>*@
        @*</div>*@
    </div>
</div>

@*<div class="ui grid container">
        @foreach (var item in Model)
        {
            <div class="four wide column ui card">
                <div class="image">
                    <img src="~/Content/Images/@item.ImageName">
                </div>
                <div class="content">
                    <a class="header">@Html.DisplayFor(modelItem => item.ContentName)</a>
                    <div class="description">
                        @Html.DisplayFor(modelItem => item.Comment)
                    </div>
                </div>
                <div class="extra content">
                    <a>
                        <i class="user icon"></i>
                        The rank of this activity is: @Html.DisplayFor(modelItem => item.Rank)
                    </a>
                </div>
            </div>
        }
    </div>*@
<div class="ui grid container">
    <div class="ui four cards">
        @foreach (var item in (IEnumerable<IEProject1.Models.Content>)ViewData["content"])
        {
            <div class="card">
                <div class="image">
                    <img src="~/Content/Images/@item.ImageName">
                </div>
                <div class="extra">
                    Rating:
                    <div class="ui rating" data-rating="@item.Popularity" data-max-rating="5"></div>
                </div>
            </div>
        }
    </div>


 </div>

IEProject1/Views/Contents/Index.cshtml
@model IEnumerable<IEProject1.Models.Content>

@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout_Semantic.cshtml";
}

<body>
    <!-- Following Menu -->
    <div class="ui large top fixed hidden menu">
        <div class="ui container">
            <a class="active item">Home</a>
            <a class="item">Sports</a>
            <a class="item">Religion</a>
            <a class="item">Yoga</a>
            <a class="item">Culture</a>
        </div>
    </div>


    <div class="pusher" style="height:100%">
        <div class="ui inverted vertical masthead center aligned segment">
            <div class="ui container">
                <div class="ui large secondary inverted pointing menu">
                    <div class="ui vertical menu">
                        <div class="ui dropdown item">
                            Menu
                            <i class="dropdown icon"></i>
                            <div class="menu">
                                <a href="@Url.Action("Index", "Places")" class="item">Sports</a>
                                <a href="@Url.Action("Index", "RPlaces")" class="item">Religion</a>
                                <a href="@Url.Action("Index", "YPlaces")" class="item">Yoga&Taichi</a>
                                <a href="@Url.Action("Details", "Places")" class="item">Food</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ui text container" style="padding-top:230px">
                <h1 class="ui inverted header">NewVics</h1>
                <h2>Do whatever you want when you want to.</h2>
                @*<div class="ui huge primary button" href="@Url.Action("Index", "Content")">See Activities<i class="right arrow icon"></i></div>*@
            </div>
        </div>
    </div>

    <div class="ui grid container" style="text-align:center;padding-top:10px">
        <div class="ui text container">
            <h1 class="ui header">See the most popular activities</h1>
            <h2>There are different kinds of activities that you can participate in. The following are the top eight most popular activies.</h2>
            <div class="ui huge violet button" style="color:white">
                <a href="@Url.Action("Create", "Contents")">See statistics</a>
            </div>
        </div>
    </div>


    @*<div class="ui grid container">
            @foreach (var item in Model)
            {
                <div class="four wide column ui card">
                    <div class="image">
                        <img src="~/Content/Images/@item.ImageName">
                    </div>
                    <div class="content">
                        <a class="header">@Html.DisplayFor(modelItem => item.ContentName)</a>
                        <div class="description">
                            @Html.DisplayFor(modelItem => item.Comment)
                        </div>
                    </div>
                    <div class="extra content">
                        <a>
                            <i class="user icon"></i>
                            The popularity of this activity is: @Html.DisplayFor(modelItem => item.Popularity)
                        </a>
                    </div>
                </div>
            }
        </div>*@
    @*<div class="ui grid container">
            <div class="ui four cards">
                @foreach (var item in (IEnumerable<IEProject1.Models.Content>)ViewData["contents"])
                {
                    <div class="card">
                        <div class="image">
                            <img src="~/Content/Images/@item.ImageName">
                        </div>
                        <div class="extra">
                            Rating:@item.Popularity
                            <div class="ui accurate star widget">
                                <div class="highlight" style="width:75%"></div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>*@
    <div class="ui grid container">
        <div class="ui four cards">
            @foreach (var item in (IEnumerable<IEProject1.Controllers.Trend>)ViewData["trends"])
            {
              <div class="card">
                <div class="content" style="text-align:center">
                    <div class="header">@item.Name</div>
                   </div>
                <div class="ui bottom attached button">
                   <i class="arrow alternate circle right icon"></i>
                   <a href="@item.Url">Go to Twitter</a>
                  </div>
                </div>
            }

        </div>
    </div>

    <div name="FieldChoose" class="ui vertical stripe segment">
        <div class="ui text container">
            <h1 class="ui header">Choose fields you like</h1>
            <h2>Now let's start and choose your favourite fiels and see some interesting activies.</h2>
        </div>
    </div>

    <div class="ui grid container">
        <div class="ui internally celled grid">
            <div class="row">
                <div class="eight wide column">
                    @*<img src="~/Content/Images/sports.jpg">*@
                    <a href="@Url.Action("Index", "Places")" class="links">
                        <img src="@Url.Content("~/Content/Images/sports.jpg")">
                    </a>
                </div>
                <div class="eight wide column">
                    @*<img src="~/Content/Images/Music.jpg">*@
                    <a href="@Url.Action("Index", "RPlaces")" class="links">
                        <img src="@Url.Content("~/Content/Images/religion.jpg")">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="eight wide column">
                    @*<img src="~/Content/Images/egames.jpg">*@
                   <a href="@Url.Action("Index", "YPlaces")" class="links">
                        <img src="@Url.Content("~/Content/Images/yoga.jpg")">
                    </a>
                </div>
                <div class="eight wide column">
                    @*<img src="~/Content/Images/photography.jpg">*@
                    <a href="@Url.Action("Details", "Places")" class="links">
                        <img src="@Url.Content("~/Content/Images/food.jpg")">
                    </a>
                </div>
            </div>
        </div>
    </div>


</body>

IEProject1/Views/Contents/Page1.cshtml
@model IEnumerable<IEProject1.Models.Content>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Homepage</title>
    </head>

    <body id="page-top">
        <!-- Navigation -->
        @*<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top" style="padding-left:0px; padding-top:11px;">
                    <i class="home icon"></i>
                    NewVics
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="#trends"> <i class="quote right icon"></i> Trends</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="#interests"> <i class="user icon"></i> My Interests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="@Url.Action("Index", "Places")"> <i class="life ring icon"></i> Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="@Url.Action("Edit", "Places")"> <i class="coffee icon"></i> Food</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@


        <header style="padding-top: 0px; overflow: hidden; height: 60%;">
            <img src="~/Content/Images/cover1_1.jpg" style=" width: 100%;" />
            <h1 style="position: absolute; top: 20%; left: 36%; font-style: italic;">Head start your new life!</h1>
            <h5 style="position: absolute; top: 27%; left: 29%;">Scroll below to know about recent trends and follow the activities you like</h5>
        </header>


        <section id="trends" class="bg-light" style="padding-top: 25px; padding-bottom: 25px;">
            <div class="ui center aligned text container">
                <h2>Current Trends</h2>
                <p>This will let you know current trending topics</p>
            </div>
            <div class="ui grid container" style="margin-top: 20px;">
                <div class="ui four cards">
                    @foreach (var item in (IEnumerable<IEProject1.Controllers.Trend>)ViewData["trends"])
                    {
                        <div class="card">
                            <div class="content" style="text-align:center">
                                <div class="header">@item.Name</div>
                            </div>
                            <div class="ui bottom attached button">
                                <i class="arrow alternate circle right icon"></i>
                                <a href="@item.Url" target="_blank">Go to Twitter</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="ui center aligned text container" style="padding-top:3%">
                <p>Do you want to see some statistic for some activities? Click here.</p>
                <div class="ui huge button" style="color:white">
                    <a href="@Url.Action("Create", "Contents")">See statistics</a>
                </div>
            </div>
        </section>

        <section id="interests" style="padding-top: 25px; padding-bottom: 25px;">
            <div class="ui center aligned text container">
                <h2>Choose your area of interest</h2>
                <p>This will help you to meet like minded people</p>
            </div>
            <div class="ui three column grid">
                <div class="column">
                    <div class="ui segment">
                        <a href="@Url.Action("Index", "Places")" class="ui large rounded image">
                            <img src="@Url.Content("~/Content/Images/sports.jpg")">
                        </a>
                    </div>
                </div>
                <div class="column">
                    <div class="ui segment">
                        <a href="@Url.Action("Edit", "Places")" class="ui large rounded image">
                            <img src="@Url.Content("~/Content/Images/food.jpg")">
                        </a>
                    </div>
                </div>
                <div class="column">
                    <div class="ui segment">
                        <a href="@Url.Action("Delete", "Places")" class="ui large rounded image">
                            <img src="@Url.Content("~/Content/Images/out123.jpg")">
                        </a>
                    </div>
                </div>
            </div>
            @*<div class="ui centered grid" style="margin-top: 20px;">
        <div class="four column centered row">
            <div class="column">
                <a href="@Url.Action("Index", "Places")" class="ui large rounded image">
                    <img src="@Url.Content("~/Content/Images/sports.jpg")">
                </a>
            </div>*@
            @*<div class="column">
            <a href="@Url.Action("Index", "RPlaces")" class="ui large rounded image">
                <img src="@Url.Content("~/Content/Images/religion.jpg")">
            </a>
        </div>*@
            @*<div class="column">
                <a href="@Url.Action("Edit", "Places")" class="ui large rounded image">
                    <img src="@Url.Content("~/Content/Images/food.jpg")">
                </a>
            </div>
        </div>*@
            @*<div class="four column centered row">
            <div class="column">
                <a href="@Url.Action("Index", "YPlaces")" class="ui large rounded image">
                    <img src="@Url.Content("~/Content/Images/yoga.jpg")">
                </a>
            </div>
            <div class="column">
                <a href="@Url.Action("Details", "Places")" class="ui large rounded image">
                    <img src="@Url.Content("~/Content/Images/food.jpg")">
                </a>
            </div>
        </div>*@
            @*</div>*@
        </section>

    </body>
</html>